Change according to README.md

diff --git a/cli-installer b/cli-installer
--- a/cli-installer
+++ b/cli-installer
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
-# Copyright  (C) 2012-2013 Alf Gaida <agaida@siduction.org>
+# Copyright  (C) 2023      Axel Konrad <emma-konrad@web.de>
+#                2012-2013 Alf Gaida <agaida@siduction.org>
 #                2012      Sebastian Görgen <zeppo@siduction.net>
 #                2009-2010 Nikolas Poniros <edhunter@sidux.com>
 #
@@ -94,7 +95,7 @@ HOSTNAME_ALLOWED_CHAR_OTHERS="0123456789.-"
 USERNAME_ALLOWED_CHARS="abcdefghijklmnopqrstuvwxyz0123456789.-"
 
 # Dont change the order of the character because it might not work with grep anymore
-NAME_NAME_NOT_ALLOWED_CHARS="]°!\"§$%&/(){}=?\`+*~#;:=,><|_^\\\[-"
+NAME_NAME_NOT_ALLOWED_CHARS="]°\"!§$%&/(){}=?\`´+*~#;:=,><|_^\\[-"
 
 PARTITION_PROG="cfdisk"
 CHECK_IF_HOME_EXISTS="no"
@@ -112,7 +113,7 @@ SWAP_PART_LIST=$(mktemp /tmp/swap_part_list.XXXXXXXX)
 
 
 if [ -f ${CONFIG_FILE} ]; then
-	echo >&2 "E: Config file exists please remove it and run the script again"
+	echo >&2 "E: Config file \"${CONFIG_FILE}\" exists please remove it and run the script again"
 	exit 1
 fi
 
@@ -131,7 +132,7 @@ fi
 
 
 ### VARIABLES NEEDED BY THE CONFIG FILE
-#----------------------------------------------------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 
 FORMAT_HD="yes"
 FILESYSTEM="ext4"
@@ -140,7 +141,7 @@ MOUNT_POINT_LIST=""
 IGNORE_DISK_SPACE="no"
 AUTO_SWAP="yes"
 SWAP_LIST=""
-REAL_NAME="foobar"
+REAL_NAME=""
 USERNAME=""
 USERPASS=""
 ROOTPASS=""
@@ -148,7 +149,6 @@ ROOTPASS=""
 HOST_NAME="siductionbox"
 SERVICES_LIST=""
 BOOT_LOADER="grub"
-BOOT_DISK="no"
 BOOT_WHERE="mbr"
 AUTOMOUNT_BOOT="yes"
 
@@ -157,7 +157,7 @@ AUTOMOUNT_BOOT="yes"
 trap "rm -f ${CONFIG_FILE}; rm -f ${PARTITIONS_LIST}; rm -f ${PARTITIONS_LIST_2}; exit 2" $SIGINT $SIGTERM
 
 ### GENERAL PURPOSE FUNCTIONS
-#----------------------------------------------------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 
 # Function to call ssft_yesno
 # $1 is the title for ssft_yesno
@@ -165,9 +165,7 @@ trap "rm -f ${CONFIG_FILE}; rm -f ${PARTITIONS_LIST}; rm -f ${PARTITIONS_LIST_2}
 # returns 0 if yes was selected != 0 otherwise
 yesno ()
 {
-	title="$1"
-	msg="$2"
-	ssft_yesno "${title}" "${msg}"
+	ssft_yesno "$1" "$2"
 	return $?
 }
 
@@ -191,11 +189,12 @@ error_msg ()
 	exit $exit_code
 }
 
+# Function to call ssft_display_message
+# $1 is the title for ssft_display_message
+# $2 is the text for ssft_display_message
 display_msg ()
 {
-	title="$1"
-	msg="$2"
-	ssft_display_message "${title}" "${msg}"
+	ssft_display_message "$1" "$2"
 }
 
 # Function to call ssft_select_multiple
@@ -226,26 +225,31 @@ select_one ()
 	return $?
 }
 
+# Function to request a password with ssft_read_password
+# $1 is the message displayed for ssft_read_password
+# returns the exit code of ssft_read_password
 input_pass ()
 {
-	title="Input Password"
-	msg="$1"
-	ssft_read_password "${title}" "${msg}"
+	ssft_read_password "Input Password" "$1"
 	return $?
 }
 
+# Function to request a text input
+# $1 is the title for ssft_read_string
+# $2 is the message displayed for ssft_read_string
+# returns the exit code of ssft_read_string
 input_string ()
 {
-	title="$1"
-	msg="$2"
-	ssft_read_string "${title}" "${msg}"
+	ssft_read_string "$1" "$2"
 	return $?
 }
 
 # Function to check the length of a string
 # $1 the string
-# $2 string type can be "user" "root" "username" "hostname" "real name"
+# $2 string type can be "user" "root" "username" "hostname"
 # $3 var to check if string is a password
+# $4 minimum length of other than password (positive integer)
+# $5 the function from where the request comes
 length_check ()
 {
 	string="$1"
@@ -545,19 +549,8 @@ custom_root ()
 }
 
 
-#escape_chars ()
-#{
-#	echo "$(echo "$1" | sed -e 's/!/\\!/g' -e 's/\"/\\"/g' -e 's/\$/\\$/g' -e 's/%/\\%/g' \
-#			      -e 's/&/\\&/g' -e 's/{/\\{/g' -e 's/(/\\(/g' -e 's/\[/\\[/g' \
-#			      -e 's/)/\\)/g' -e 's/]/\\]/g' -e 's/=/\\=/g' -e 's/}/\\}/g' \
-#			      -e 's/?/\\?/g' -e 's/\\/\\/g' -e 's/*/\\*/g' -e 's/+/\\+/g' \
-#			      -e 's/~/\\~/g' -e "s/'/\\'/g" -e 's/#/\\#/g' -e 's/>/\\>/g' \
-#			      -e 's/</\\</g' -e 's/`/\\`/g' -e 's/|/\\|/g' -e 's/;/\\;/g' \
-#			      -e 's/-/\\-/g' )"
-#}
-
 ### FUNCTIONS TO GET THE VALUES FOR THE VARIABLES THAT WILL BE PASSED LATER TO THE CONFIG FILE
-#-------------------------------------------------------------------------------------------------------------------------
+#---------------------------------------------------------------------------------------------
 
 # Only for root partition
 format_root ()
@@ -805,42 +798,46 @@ select_swap ()
 	fi
 }
 
-#input_real_name ()
-#{
-#	title="Input Real Name"
-#	msg="Please enter your real name"
+input_real_name ()
+{
+	title="Input Real Name"
+	msg="Please enter your real name"
 
-#	input_string "${title}" "${msg}"
-#	if [ $? -eq 0 ]; then
-#		name="${SSFT_RESULT}"
-#	fi
+	input_string "${title}" "${msg}"
+	while [ $? -ne 0 ]; do
+		yesno "No real name" "Continue without real name?"
+		if [ $? -eq 0 ]; then
+			printf "%s\n" "OK, no real name"
+			return 0
+		else
+			input_string "${title}" "${msg}"
+			if [ $? -ne 0 ]; then
+				error_msg "Multiple input errors for 'real name" "1"
+			fi
+		fi
+	done
 
-#	length_check "${name}" "real name" "no" "1" "${title}"
-#	# Need this as length_check sets REAL_NAME but I still
-#	# need to check chars
-#	name="${REAL_NAME}"
-#	# Make sure that name contains only valid characters
-#	while [ -n "$( echo "${name}" | grep "[${NAME_NAME_NOT_ALLOWED_CHARS}]" )" ]
-#		do
-#			title="Input Real Name"
-#			msg="Your input contains characters which are not allowed
-#				Characters which are not allowed are:
+	name="${SSFT_RESULT}"
+	# Make sure that name contains only valid characters
+	while [ -n "$( echo "${name}" | grep "[${NAME_NAME_NOT_ALLOWED_CHARS}]" )" ]
+		do
+		title="Real Name, not allowed Characters"
+		msg="Your input contains characters which are not allowed
+			Characters which are not allowed are:
 
-#				${NAME_NAME_NOT_ALLOWED_CHARS}
+			${NAME_NAME_NOT_ALLOWED_CHARS}
 
-#				Please enter again your real name"
-#			input_string "${title}" "${msg}"
-#			if [ $? -eq 0 ]; then
-#				name="${SSFT_RESULT}"
-#			fi
+			Please enter again your real name"
+		input_string "${title}" "${msg}"
+			if [ $? -eq 0 ]; then
+				name="${SSFT_RESULT}"
+			fi
+		done
 
-#			length_check "${name}" "real name" "no" "1" "${title}"
+	## Used to escape spaces and quotes (')
+	REAL_NAME=$( echo "$name" | sed -e "s/ /\\\ /g" -e "s/'/\\\'/g" )
 
-#			name="${REAL_NAME}" # length_check set the REAL_NAME but i still need to escape chars
-#		done
-#	## Used to escape spaces and quotes (')
-#	REAL_NAME=$( echo "$name" | sed -e "s/ /\\\ /g" -e "s/'/\\\'/g" )
-#}
+}
 
 input_username ()
 {
@@ -901,12 +898,6 @@ input_user_pass ()
 	fi
 
 	compare_pass "${USERPASS}" "${pass2}" "user"
-	# If the passwords dont pass the test at the first time then
-	# USERPASS will be set by length_check which is called in compare_pass
-	#pass1="${USERPASS}"
-	#pass2="$(escape_chars "$pass1")"
-	## create hashed password and escape $
-	#USERPASS=$( echo "$pass2" | mkpasswd --method=sha-256 -s | sed  's/\$/\\$/g' )
 	USERPASS="$( mkpasswd --method=sha-256 "${USERPASS}" | sed 's/\$/\\$/g' )"
 }
 
@@ -935,12 +926,6 @@ input_root_pass ()
 	fi
 
 	compare_pass "${ROOTPASS}" "${pass2}" "root"
-	# If the passwords dont pass the test at the first time then
-	# ROOTPASS will be set by length_check which is called in compare_pass
-	#pass1="${ROOTPASS}"
-	#pass2="$(escape_chars "$pass1")"
-	## create hashed password and escape $
-	#ROOTPASS=$( echo "$pass2" | mkpasswd --method=sha-256 -s | sed  's/\$/\\$/g' )
 	ROOTPASS="$( mkpasswd --method=sha-256 "${ROOTPASS}" | sed 's/\$/\\$/g' )"
 }
 
@@ -995,19 +980,6 @@ input_services ()
 	fi
 }
 
-#set_bootloader () {}
-
-# Ask the user if he wants to create a boot disk
-#create_boot_disk ()
-#{
-#	title="Create boot-disk"
-#	msg="Do you want to create a boot-disk?"
-#	yesno "${title}" "${msg}"
-#	if [ $? -eq 0 ]; then
-#		BOOT_DISK="yes"
-#	fi
-#}
-
 # Ask the user where he wants to place the boot-loader mbr or partition
 place_boot_loader ()
 {
@@ -1039,7 +1011,7 @@ auto_mount_partitions ()
 
 write_config ()
 {
-	echo "REGISTERED=' SYSTEM_MODULE HD_MODULE HD_FORMAT HD_FSTYPE HD_CHOICE HD_MAP HD_IGNORECHECK SWAP_MODULE SWAP_AUTODETECT SWAP_CHOICES NAME_MODULE NAME_NAME USER_MODULE USER_NAME USERPASS_MODULE USERPASS_CRYPT ROOTPASS_MODULE ROOTPASS_CRYPT HOST_MODULE HOST_NAME SERVICES_MODULE SERVICES_START BOOT_MODULE BOOT_LOADER BOOT_DISK BOOT_WHERE AUTOLOGIN_MODULE INSTALL_READY HD_AUTO'" > ${CONFIG_FILE}
+	echo "REGISTERED=' SYSTEM_MODULE HD_MODULE HD_FORMAT HD_FSTYPE HD_CHOICE HD_MAP HD_IGNORECHECK SWAP_MODULE SWAP_AUTODETECT SWAP_CHOICES NAME_MODULE NAME_NAME USER_MODULE USER_NAME USERPASS_MODULE USERPASS_CRYPT ROOTPASS_MODULE ROOTPASS_CRYPT HOST_MODULE HOST_NAME SERVICES_MODULE SERVICES_START BOOT_MODULE BOOT_LOADER BOOT_WHERE AUTOLOGIN_MODULE INSTALL_READY HD_AUTO'" > ${CONFIG_FILE}
 
 	echo >> ${CONFIG_FILE}
 
@@ -1134,13 +1106,6 @@ write_config ()
 
 	echo >> ${CONFIG_FILE}
 
-	echo "# If set to 'yes' a boot disk will be created!" >> ${CONFIG_FILE}
-	echo "# Possible are: yes|no" >> ${CONFIG_FILE}
-	echo "# Default value is: no" >> ${CONFIG_FILE}
-	echo "BOOT_DISK='${BOOT_DISK}'" >> ${CONFIG_FILE}
-
-	echo >> ${CONFIG_FILE}
-
 	echo "# Where the Boot-Loader will be installed" >> ${CONFIG_FILE}
 	echo "# Possible are: mbr|partition" >> ${CONFIG_FILE}
 	echo "# Default value is: mbr" >> ${CONFIG_FILE}
@@ -1159,7 +1124,7 @@ write_config ()
 }
 
 ### MAIN
-#--------------------------------------------------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 
 format_disk
 
@@ -1199,11 +1164,6 @@ input_root_pass
 input_hostname
 
 input_services
-
-#set_bootloader
-
-# Leave disabled for now
-#create_boot_disk
 
 # If the disk choosen as root is USB then force partition
 if [ "${IS_DISK_USB}" = "no" ]; then
@@ -1246,4 +1206,3 @@ fi
 rm -f $ERROR_LOG
 
 exit 0
-
